version: "3.4"


services:
  app:
    restart: unless-stopped
    image: kachalov/cinnabuns-final:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 5000:80
    env_file: app.env
    labels:
      traefik.enable: "true"
      traefik.backend: "cinnabuns.hack"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${HOST}"
  
  dev:
    restart: unless-stopped
    image: kachalov/cinnabuns-final:dev-${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      target: publish
    env_file: app.env
    command: dotnet ef database update
  
  pg:
    image: postgres:11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
