version: "2.1"


services:
  app:
    restart: unless-stopped
    image: kachalov/cinnabuns-final:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
#    ports:
#      - 5000:80
    env_file: app.env
    labels:
      traefik.enable: "true"
      traefik.backend: "cinnabuns.hack"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${HOST}"
